export const destinationMeta = {
  Bangkok: {
    flag: "🇹🇭",
    name: "Bangkok, Thailand",
    region: "Southeast Asia",
    currency: "Thai Baht (THB)",
    tz: "GMT+7",
    language: "Thai",
    safety: "6.8",
    alerts: "12",
    cost: "Low",
    temp: "32°C",
  },
  Bali: {
    flag: "🇮🇩",
    name: "Bali, Indonesia",
    region: "Southeast Asia",
    currency: "Indonesian Rupiah (IDR)",
    tz: "GMT+8",
    language: "Indonesian",
    safety: "7.1",
    alerts: "9",
    cost: "Low",
    temp: "29°C",
  },
  Hanoi: {
    flag: "🇻🇳",
    name: "Hanoi, Vietnam",
    region: "Southeast Asia",
    currency: "Vietnamese Dong (VND)",
    tz: "GMT+7",
    language: "Vietnamese",
    safety: "7.4",
    alerts: "7",
    cost: "Low",
    temp: "28°C",
  },
  Tokyo: {
    flag: "🇯🇵",
    name: "Tokyo, Japan",
    region: "East Asia",
    currency: "Japanese Yen (JPY)",
    tz: "GMT+9",
    language: "Japanese",
    safety: "9.1",
    alerts: "3",
    cost: "High",
    temp: "24°C",
  },
  "Siem Reap": {
    flag: "🇰🇭",
    name: "Siem Reap, Cambodia",
    region: "Southeast Asia",
    currency: "Cambodian Riel (KHR)",
    tz: "GMT+7",
    language: "Khmer",
    safety: "6.5",
    alerts: "8",
    cost: "Low",
    temp: "31°C",
  },
  Rome: {
    flag: "🇮🇹",
    name: "Rome, Italy",
    region: "Southern Europe",
    currency: "Euro (EUR)",
    tz: "GMT+2",
    language: "Italian",
    safety: "7.0",
    alerts: "11",
    cost: "High",
    temp: "26°C",
  },
  Barcelona: {
    flag: "🇪🇸",
    name: "Barcelona, Spain",
    region: "Southern Europe",
    currency: "Euro (EUR)",
    tz: "GMT+2",
    language: "Spanish",
    safety: "6.9",
    alerts: "10",
    cost: "Medium",
    temp: "25°C",
  },
  "Kuala Lumpur": {
    flag: "🇲🇾",
    name: "Kuala Lumpur, Malaysia",
    region: "Southeast Asia",
    currency: "Malaysian Ringgit (MYR)",
    tz: "GMT+8",
    language: "Malay",
    safety: "8.2",
    alerts: "5",
    cost: "Low",
    temp: "31°C",
  },
  Singapore: {
    flag: "🇸🇬",
    name: "Singapore",
    region: "Southeast Asia",
    currency: "Singapore Dollar (SGD)",
    tz: "GMT+8",
    language: "English",
    safety: "9.4",
    alerts: "2",
    cost: "High",
    temp: "30°C",
  },
  Prague: {
    flag: "🇨🇿",
    name: "Prague, Czech Republic",
    region: "Central Europe",
    currency: "Czech Koruna (CZK)",
    tz: "GMT+2",
    language: "Czech",
    safety: "7.3",
    alerts: "6",
    cost: "Medium",
    temp: "18°C",
  },
  Kathmandu: {
    flag: "🇳🇵",
    name: "Kathmandu, Nepal",
    region: "South Asia",
    currency: "Nepalese Rupee (NPR)",
    tz: "GMT+5:45",
    language: "Nepali",
    safety: "6.8",
    alerts: "7",
    cost: "Low",
    temp: "22°C",
  },
  Colombo: {
    flag: "🇱🇰",
    name: "Colombo, Sri Lanka",
    region: "South Asia",
    currency: "Sri Lankan Rupee (LKR)",
    tz: "GMT+5:30",
    language: "Sinhala",
    safety: "7.0",
    alerts: "6",
    cost: "Low",
    temp: "30°C",
  },
};

export function getDestination(city) {
  return (
    destinationMeta[city] || {
      flag: "🌍",
      name: city,
      region: "Unknown",
      currency: "—",
      tz: "—",
      language: "—",
      safety: "—",
      alerts: "—",
      cost: "—",
      temp: "—",
    }
  );
}

export const alerts = [
  {
    name: "Tuk-Tuk Free Temple Tour",
    level: "high",
    badge: "High risk",
    desc: "Driver offers a free city tour, then takes you to gem or tailor shops with extreme pressure to buy, averaging $200+ per victim.",
    avoid: "Refuse all free tour offers. Use the Grab app only.",
    source: "r/solotravel · reported 4× this week",
  },
  {
    name: "Taxi No-Meter Scam",
    level: "medium",
    badge: "Medium",
    desc: "Driver claims the meter is broken, then charges 3 to 5× fair price, especially from Suvarnabhumi airport late at night.",
    avoid: "Insist on the meter or book Grab before leaving arrivals.",
    source: "r/ThailandTourism · reported 7× this week",
  },
  {
    name: "Or Tor Kor Market, Safe Pick",
    level: "low",
    badge: "Tip",
    desc: "The safest, highest quality street food in Bangkok. Local prices, excellent hygiene, open mornings until 2pm.",
    avoid: "Best time is 7 to 10am. Avoid the tourist food courts nearby.",
    source: "r/solotravel · 847 upvotes",
  },
];

export const tips = [
  {
    icon: "taxi",
    title: "Transport, always use Grab",
    desc: "Fixed prices, tracked rides, no negotiation. Airport to city is roughly 280 THB versus 600+ with street taxis.",
    saving: "Saves about $9 per airport ride",
  },
  {
    icon: "food",
    title: "Food, Or Tor Kor Market",
    desc: "The safest, highest quality street food. Local prices, excellent variety. Avoid the tourist food courts nearby.",
    saving: "50% cheaper than tourist restaurants",
  },
  {
    icon: "money",
    title: "Money, Kasikorn ATM only",
    desc: "Lowest foreign card fees in Thailand. Superrich exchange booths on Silom give the best cash rates.",
    saving: "Saves $4 to $8 per withdrawal",
  },
];

export const recent = [
  { name: "Fake Parking Attendant Scam", dest: "Bali, Indonesia · Tanah Lot Temple", level: "High", time: "2h ago", tone: "danger" },
  { name: "Currency Shortchanging at Money Changers", dest: "Hanoi, Vietnam · Old Quarter", level: "Medium", time: "4h ago", tone: "warning" },
  { name: "Ben Thanh Market, Safe for Food", dest: "Ho Chi Minh City, Vietnam", level: "Tip", time: "6h ago", tone: "safe" },
  { name: "Bracelet Gifting Scam, New Reports", dest: "Rome, Italy · Trevi Fountain area", level: "High", time: "8h ago", tone: "danger" },
  { name: "ATM Skimming Device Found", dest: "Prague, Czech Republic · Old Town Square", level: "High", time: "12h ago", tone: "info" },
];

export const cities = [
  { flag: "🇹🇭", name: "Bangkok", score: "6.8", tone: "ok" },
  { flag: "🇮🇩", name: "Bali", score: "7.1", tone: "ok" },
  { flag: "🇻🇳", name: "Hanoi", score: "7.4", tone: "ok" },
  { flag: "🇯🇵", name: "Tokyo", score: "9.1", tone: "good" },
  { flag: "🇰🇭", name: "Siem Reap", score: "6.5", tone: "ok" },
  { flag: "🇮🇹", name: "Rome", score: "7.0", tone: "ok" },
  { flag: "🇪🇸", name: "Barcelona", score: "6.9", tone: "ok" },
  { flag: "🇲🇾", name: "Kuala Lumpur", score: "8.2", tone: "good" },
  { flag: "🇸🇬", name: "Singapore", score: "9.4", tone: "good" },
  { flag: "🇨🇿", name: "Prague", score: "7.3", tone: "ok" },
  { flag: "🇳🇵", name: "Kathmandu", score: "6.8", tone: "ok" },
  { flag: "🇱🇰", name: "Colombo", score: "7.0", tone: "ok" },
];